### ISSUE TITLE
container starts up, runs a bit, then dies

### ISSUE THREAD

**Issue by NeoMatrixJR** [tgoetheyn/Docker-NagiosXI#4]
What do I need to do to keep this running after it initializes?  Also, what directories need to be mounted to maintain my setup when upgrading/rebuilding my container?

**Comment by olivier2012** [comment]
same problem .  I think  it happened at  start.sh , when  the script run finish , the container  stoped.

**Comment by olivier2012** [comment]
I tried  just uncomment the  # tail line   in start.sh   , it is working .  thanks

**Comment by NeoMatrixJR** [comment]
Latest commit fixes this
